# [START runtime]
runtime: python
env: flex
entrypoint: gunicorn -b :$PORT cying.wsgi

beta_settings:
    cloud_sql_instances: 'daily-186904:australia-southeast1:daily-instance' 

runtime_config:
  python_version: 3
# [END runtime]