# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='order',
            new_name='priority',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='order',
            new_name='priority',
        ),
    ]
