# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0002_auto_20171118_0856'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority']},
        ),
        migrations.AlterField(
            model_name='interval',
            name='end',
            field=models.DateTimeField(null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='interval',
            name='start',
            field=models.DateTimeField(null=True, verbose_name='start time'),
        ),
    ]
