# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0003_auto_20171118_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 18, 0, 47, 16, 952864, tzinfo=utc), verbose_name='start time'),
            preserve_default=False,
        ),
    ]
