# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0004_auto_20171118_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interval',
            name='duration',
            field=models.DurationField(null=True),
        ),
    ]
